import type { Project } from '@/types'

export const projects: Project[] = [
  {
    slug: 'muhasabah',
    title: 'Muhasabah',
    description: 'Self-reflection and habit tracking platform. Built with React and FastAPI, featuring a PostgreSQL backend and a clean, minimal UI focused on daily journaling and progress tracking.',
    tags: ['React', 'FastAPI', 'PostgreSQL', 'Tailwind CSS'],
    github: 'https://github.com/rushdv/muhasabah',
    live: 'https://muhasabah.vercel.app',
    image: '/projects/muhasabah.png',
    featured: true,
  },
  {
    slug: 'netscope-live',
    title: 'NetScope-Live',
    description: 'Real-time network traffic visualizer with an interactive dashboard. Uses Scapy for packet capture and WebSockets to stream live data to the React frontend.',
    tags: ['Python', 'Scapy', 'React', 'WebSockets'],
    github: 'https://github.com/rushdv/NetScope-Live',
    image: '/projects/NetScope-live.png',
    featured: true,
  },
  {
    slug: 'nexum',
    title: 'Nexum',
    description: 'Scalable social media application with a focus on performance and clean component architecture. Supports real-time interactions and a responsive feed.',
    tags: ['React', 'Vite', 'Tailwind CSS', 'DaisyUI'],
    github: 'https://github.com/rushdv/nexum',
    image: '/projects/nexum.png',
    featured: true,
  },
  {
    slug: 'debug-ai',
    title: 'DebugAI',
    description: 'Command-line tool that leverages the Gemini AI API to analyze error messages and suggest fixes. Installable via pip and works across any Python project.',
    tags: ['Python', 'Gemini AI', 'CLI'],
    github: 'https://github.com/rushdv/debug-ai',
    featured: false,
  },
  {
    slug: 'brain-vault',
    title: 'Brain Vault',
    description: 'Personal knowledge base for technical documentation and research notes. Structured for fast lookup and built to grow alongside ongoing learning.',
    tags: ['React', 'Vite', 'Vercel'],
    github: 'https://github.com/rushdv/brain-vault',
    live: 'https://brain-vault-iota.vercel.app',
    image: '/projects/brainvault.png',
    featured: false,
  },
  {
    slug: 'securepass',
    title: 'SecurePass Manager',
    description: 'React-based password manager with client-side encryption, a clean UI, and smooth animations. No data leaves the browser.',
    tags: ['React', 'CryptoJS', 'Tailwind CSS', 'Framer Motion'],
    github: 'https://github.com/rushdv/securepass',
    featured: false,
  },
]
